# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sectores_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import uic
from PyQt5.QtWidgets import QDialog

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'sectores_dialog_base.ui'))

class SectoresDialog(QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        super(SectoresDialog, self).__init__(parent)
        self.setupUi(self)
        

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(873, 466)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(480, 420, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.entrada = QtWidgets.QComboBox(Dialog)
        self.entrada.setGeometry(QtCore.QRect(170, 20, 621, 22))
        self.entrada.setObjectName("entrada")
        self.numsect1 = QtWidgets.QSpinBox(Dialog)
        self.numsect1.setGeometry(QtCore.QRect(140, 100, 42, 22))
        self.numsect1.setObjectName("numsect1")
        self.numsect2 = QtWidgets.QSpinBox(Dialog)
        self.numsect2.setGeometry(QtCore.QRect(140, 140, 42, 22))
        self.numsect2.setObjectName("numsect2")
        self.numsect3 = QtWidgets.QSpinBox(Dialog)
        self.numsect3.setGeometry(QtCore.QRect(140, 180, 42, 22))
        self.numsect3.setObjectName("numsect3")
        self.numsect4 = QtWidgets.QSpinBox(Dialog)
        self.numsect4.setGeometry(QtCore.QRect(140, 220, 42, 22))
        self.numsect4.setObjectName("numsect4")
        self.numsect5 = QtWidgets.QSpinBox(Dialog)
        self.numsect5.setGeometry(QtCore.QRect(140, 260, 42, 22))
        self.numsect5.setObjectName("numsect5")
        self.numsect6 = QtWidgets.QSpinBox(Dialog)
        self.numsect6.setGeometry(QtCore.QRect(140, 300, 42, 22))
        self.numsect6.setObjectName("numsect6")
        self.nivel = QtWidgets.QComboBox(Dialog)
        self.nivel.setGeometry(QtCore.QRect(170, 50, 161, 22))
        self.nivel.setObjectName("nivel")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 20, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 50, 121, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(60, 100, 101, 20))
        self.label_3.setObjectName("label_3")
        self.botonentrada = QtWidgets.QToolButton(Dialog)
        self.botonentrada.setGeometry(QtCore.QRect(800, 20, 31, 21))
        self.botonentrada.setObjectName("botonentrada")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(250, 90, 581, 301))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(60, 140, 101, 20))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(60, 180, 101, 20))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(60, 220, 101, 20))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(60, 260, 101, 20))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(60, 300, 101, 20))
        self.label_14.setObjectName("label_14")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Capa Entrada"))
        self.label_2.setText(_translate("Dialog", "Campo a sectorizar"))
        self.label_3.setText(_translate("Dialog", "Sectores_ N1"))
        self.botonentrada.setText(_translate("Dialog", "..."))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "$id"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Nivel"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Longitud-nivel"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Nº Sectores"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Longitud-sector"))
        self.label_10.setText(_translate("Dialog", "Sectores_ N2"))
        self.label_11.setText(_translate("Dialog", "Sectores_ N3"))
        self.label_12.setText(_translate("Dialog", "Sectores_ N4"))
        self.label_13.setText(_translate("Dialog", "Sectores_ N5"))
        self.label_14.setText(_translate("Dialog", "Sectores_ N6"))
